name: Build, Test & Pack nuget

on:
  workflow_call:
    inputs:
      NuGetDirectory:
        description: 'Path to Nuget directory'
        type: string
        required: true

jobs:
  build_test_and_pack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches entire history, so we can analyze commits since last tag
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test on .netcoreapp3.1
        run: dotnet test -c Release -f netcoreapp3.1 --no-build --verbosity normal
      - name: Test on .net6.0
        run: dotnet test -c Release -f netcoreapp3.1 --no-build --verbosity normal
      - name: Calc nuget package version
        id: calc-nuget-version
        run: echo "NugetPackageVersion=$(git describe --tags --abbrev=1 | sed 's/-/./')" >> $GITHUB_ENV
      - name: Pack nuget
        run: dotnet pack -c Release --no-build -v minimal -o ${{ inputs.NuGetDirectory }} -p:PackageVersion=${{ env.NugetPackageVersion }}
      - uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ inputs.NuGetDirectory }}/*.nupkg